<!DOCTYPE html>
<html>
<head>
	<title>2FA Check</title>
	<link rel="stylesheet" type="text/css" href="./css/style.css">
</head>
<body>
     <form action="./function.php" method="post">
		<input type="hidden" name="f" value="login" />
        <input type="hidden" name="type" value="2fa" />

     	<h2>TWO-Factor Authentication</h2>

     	<?php if (isset($_POST['error'])) { ?>
     		<p class="error"><?php echo $_POST['error']; ?></p>
     	<?php } ?>

		<?php if (isset($_POST['message'])) { ?>
            <p class="success"><?php echo $_POST['message']; ?></p>
        <?php } ?>

     	<p>Enter the One Time Password (OTP) generated by your Authenticator App.</p>
     	<input type="text" name="otpCode" placeholder="Enter OTP" required><br>

     	<button type="submit">Login</button>
     </form>
</body>
</html>