<?php 
    session_start();
    require_once "./includes/includes.php";

    $user = new user($_SESSION['id']);

    if(!empty($user->twoFactorAuthKey)) {
        $user->save([
            "twoFactorAuthKey" => null
        ]);

        if(!$user->errors) {
            $_SESSION['twoFactorAuth'] = null;

            header('Location: ./home.php');
            exit;

        } else {
            echo("<form name='redir_form' action='./home.php' method='post'>");
            echo("<input type='hidden' name='error' value='There was an error turning off 2FA.'>");
            echo("</form> <script language='javascript'> document.redir_form.submit(); </script>");
        }
    }

    $authenticator = new googleAuthenticator();

    $secret = $authenticator->createSecret();
    $qrCodeUrl = $authenticator->getQRCodeGoogleUrl(
        $_SESSION['email'],
        $secret,
        "Hyewon's Dev Site"
    );
?>

<!DOCTYPE html>
<html>
<head>
	<title>2FA settings</title>
	<link rel="stylesheet" type="text/css" href="./css/style.css">
</head>
<body>
    <form class="twoFactor-form" action="./function.php" method="post">
		<input type="hidden" name="f" value="twoFactorAuth" />
        <input type="hidden" name="secretCode" value="<?= $secret ?>" />

        <h2 class="twoFactor-title">Two-Factor Authentication (2FA)</h2>
		<p class="twoFactor-detail">Two-Factor Authentication provides an additional layer of security by requiring a verification code whenever you sign in.</p>

        <h2 class="twoFactor-title">Why do I need this?</h2>
        <p class="twoFactor-detail">
            Passwords can get stolen, especially if you use the same one for multiple sites. Two-Factor Authentication provides you with an extra layer of security so that your account will remain secure even if your password is compromised.
        </p>

        <h2 class="twoFactor-title">How does it work?</h2>
        <p class="twoFactor-detail">
            After you turn on Two-Factor Authentication for your account, you will be asked one more step whenever you sign in:
        </p>
        <ol class="twoFactor-detail" type='1'>
            <li>As usual, enter your password.</li>
            <li>Check OTP Code in your Authenticator App.</li>
            <li>Enter the OTP, and complete your Sign-In.</li>
        </ol>

        <h2 class="twoFactor-title">How to set?</h2>
        <section class="twoFactor-section">
            <?php if (isset($_POST['error'])) { ?>
                <p class="error"><?php echo $_POST['error']; ?></p>
            <?php } ?>

            <p class="twoFactor-detail">1. <b>Open</b> your Authenticator App.</p>
            <p class="twoFactor-detail">
                2. <b>Add</b> an account within the app, and <b>scan</b> the QR code below.<br>
                <img class="twoFactor-qr" src="<?= $qrCodeUrl ?>"/>
            </p>
            <p class="twoFactor-detail">
                3. <b>Enter</b> the 6-digit OTP code generated by the app.
                <input type="text" name="otpCode" placeholder="OTP Code" required><br>
            </p>
        </section>

     	<button type="submit">Confirm</button>
    </form>
</body>
</html>